#!/usr/bin/env node
/* The applier's refusals. Run: node scripts/apply.test.js
 *
 * scripts/apply.js is the only code path that can put a file on this site without a person
 * having read it. Everything here is a NEGATIVE test: not "does it apply a good plan" but
 * "does it refuse a bad one". A false negative in the gate wastes a pulse. A false positive
 * in the allowlist puts something on a public court record.
 */
'use strict';
const fs = require('fs'), path = require('path'), zlib = require('zlib'), crypto = require('crypto');
const { safePath, parsePlan, scrubbedEnv, FORBIDDEN, ALLOWED } = require('./apply.js');

let pass = 0; const fails = [];
const ok = (name, cond, extra) => { if (cond) pass++; else fails.push(name + (extra ? ' — ' + extra : '')); };
const eq = (got, want, name) => ok(name, got === want, 'got ' + JSON.stringify(got) + ', want ' + JSON.stringify(want));

console.log('\n--- the allowlist: paths a handoff may never write ---');
const forbidden = [
  '.github/workflows/pulse.yml', '.github/workflows/x.yml', '.git/config', '.git/hooks/pre-commit',
  'EDITORIAL.md', 'AGENT.md', 'STYLE.md', 'SECURITY.md',   // the red lane: policy, not code
  'CNAME', 'SUBMIT_ENDPOINT', 'INDEXNOW_KEY', '.gitignore',
  'autodeploy.bat', 'autodeploy-silent.vbs', 'install-autodeploy.bat', 'deploy.bat',
  'public/index.html', 'node_modules/x/index.js',
];
for (const p of forbidden) eq(safePath(p), null, 'refuses ' + p);

// Refused by ALLOWED alone — real files that simply are not in a tree a handoff may write.
// Kept separate from the list above so each defence is asserted by the thing that provides it.
const unlisted = ['README.md', 'GROWTH.md', 'preview.html', 'package.json', 'x.js'];
for (const p of unlisted) eq(safePath(p), null, 'refuses ' + p + ' (not in an allowed tree)');

console.log('--- and the ways a path can lie about where it goes ---');
for (const p of [
  '../outside.js', 'scripts/../../etc/passwd', 'data/../.github/workflows/x.yml',
  '/etc/passwd', '/data/x.json', 'C:/Windows/system32/x', 'c:\\windows\\x',
  '..', './..', 'scripts/ok/../../../x', '', null, undefined, 42, {},
] ) eq(safePath(p), null, 'refuses traversal/absolute: ' + JSON.stringify(p));

// Backslashes are normalised, so a Windows-style path cannot smuggle past a forward-slash rule.
eq(safePath('.github\\workflows\\x.yml'), null, 'refuses a backslash path into .github');
eq(safePath('data\\cases\\x\\case.json'), 'data/cases/x/case.json', 'normalises a backslash path it does allow');

console.log('--- what it may write ---');
for (const p of [
  'data/cases/lindsay-clancy/days.json', 'scripts/board.test.js', 'scripts/build.js',
  'docs/QUEUE-SETUP.md', 'review/dev-log-2026-08-22.md',
]) eq(safePath(p), p, 'allows ' + p);

// The two lists are separate defences and they must be separately load-bearing. Most forbidden
// paths also happen to fall outside every allowed tree, so deleting FORBIDDEN entirely changed
// no result here — found by mutation, and it means the list would silently stop protecting
// anything the moment someone widened ALLOWED. So: assert the patterns directly, and keep
// entries that live INSIDE an allowed tree, where only FORBIDDEN can refuse them.
const denies = p => FORBIDDEN.some(re => re.test(String(p).replace(/\\/g, '/')));
for (const p of forbidden) ok('FORBIDDEN itself matches ' + p, denies(p), 'only ALLOWED was refusing it');

console.log('--- and the ones inside an allowed tree, where only FORBIDDEN can stop them ---');
for (const p of [
  'scripts/apply.js',              // a plan rewriting the applier is judged by rules it wrote
  'scripts/queue.js',
  'scripts/apply.test.js',         // ...or deleting the tests that judge it
  'scripts/queue.test.js',
  'scripts/worker/ourgavel-submit.js',   // ...or weakening the auth that let it in
]) {
  eq(safePath(p), null, 'refuses ' + p);
  ok('FORBIDDEN is what refuses ' + p, denies(p) && ALLOWED.some(re => re.test(p)),
    'this path IS in an allowed tree, so only FORBIDDEN can stop it');
}
ok('public/ is forbidden even though it is a real tree', safePath('public/x.html') === null,
  'public/ is generated by build.js; a committed copy is always a bug');
ok('a plan may still patch the generator', safePath('scripts/build.js') === 'scripts/build.js');
ok('a plan may still add a test', safePath('scripts/board.test.js') === 'scripts/board.test.js');

console.log('--- the hash is over the bytes the Worker was handed ---');
const mkPlan = (obj, opts = {}) => {
  const raw = opts.gzip === false ? Buffer.from(JSON.stringify(obj)) : zlib.gzipSync(Buffer.from(JSON.stringify(obj)));
  const sha = opts.sha || crypto.createHash('sha256').update(raw).digest('hex');
  return ['### Lane', 'seo', '', '### SHA-256 of the decoded payload', sha,
    '', '### Payload (base64 of a gzipped JSON apply-plan)', '```', raw.toString('base64'), '```'].join('\n');
};
const GOOD = { v: 1, commit: 'x: y', files: [{ path: 'scripts/a.js', b64: '' }] };

const plan = parsePlan(mkPlan(GOOD));
eq(plan.commit, 'x: y', 'a well-formed gzipped plan parses');
eq(parsePlan(mkPlan(GOOD, { gzip: false })).commit, 'x: y', 'an uncompressed plan parses too');

const throws = (fn, match, name) => {
  try { fn(); fails.push(name + ' — did not throw'); }
  catch (e) { ok(name, match.test(e.message), 'threw: ' + e.message.slice(0, 90)); }
};
throws(() => parsePlan(mkPlan(GOOD, { sha: 'b'.repeat(64) })), /mismatch/i, 'refuses a payload whose hash does not match');
throws(() => parsePlan(mkPlan(GOOD, { sha: 'abc' })), /SHA-256/i, 'refuses a truncated hash');
throws(() => parsePlan(mkPlan(GOOD, { sha: 'z'.repeat(64) })), /SHA-256/i, 'refuses a non-hex hash');
throws(() => parsePlan('### Lane\nseo\n'), /SHA-256/i, 'refuses an issue with no hash heading');
throws(() => parsePlan(mkPlan({ v: 2, commit: 'x', files: [{ path: 'scripts/a.js' }] })), /version/i, 'refuses an unknown plan version');
throws(() => parsePlan(mkPlan({ v: 1, commit: 'x', files: [] })), /writes no files/i, 'refuses a plan that writes nothing');
throws(() => parsePlan(mkPlan({ v: 1, files: [{ path: 'scripts/a.js' }] })), /commit message/i, 'refuses a plan with no commit message');

// One flipped bit anywhere in the payload must fail the hash.
const body = mkPlan(GOOD);
const b64line = body.split('\n').find(l => l.length > 40 && /^[A-Za-z0-9+/=]+$/.test(l));
const flipped = body.replace(b64line, b64line.slice(0, 8) + (b64line[8] === 'A' ? 'B' : 'A') + b64line.slice(9));
throws(() => parsePlan(flipped), /mismatch|gunzip|JSON|invalid/i, 'one corrupted character fails the hash');

console.log('--- the plan\'s own code never sees our credentials ---');
const before = { ...process.env };
Object.assign(process.env, {
  GITHUB_TOKEN: 'ghs_secret', GH_TOKEN: 'ghp_secret', QUEUE_TOKEN: 'q', ACTIONS_RUNTIME_TOKEN: 'a',
  AWS_SECRET_ACCESS_KEY: 's', MY_API_KEY: 'k', NPM_PASSWORD: 'p', INPUT_FOO: 'i', RUNNER_TEMP: '/t',
  PATH: before.PATH, HOME: before.HOME || '/root',
});
const env = scrubbedEnv();
for (const k of ['GITHUB_TOKEN', 'GH_TOKEN', 'QUEUE_TOKEN', 'ACTIONS_RUNTIME_TOKEN', 'AWS_SECRET_ACCESS_KEY', 'MY_API_KEY', 'NPM_PASSWORD', 'INPUT_FOO', 'RUNNER_TEMP']) {
  ok('scrubbed ' + k, !(k in env), 'still present as ' + env[k]);
}
ok('kept PATH', !!env.PATH);
ok('marked as sandboxed', env.OURGAVEL_SANDBOX === '1');
ok('no value of any scrubbed var survives under another name',
  !Object.values(env).some(v => v === 'ghs_secret' || v === 'ghp_secret'));
process.env = before;

console.log('--- the second allowlist pass exists ---');
// The first pass checks what a plan DECLARES. A plan that runs a script can write anywhere, so
// the check that matters is against `git status` afterwards. Assert the source still does that,
// because losing it would leave every other test in this file passing.
const src = fs.readFileSync(path.join(__dirname, 'apply.js'), 'utf8');
ok('git status is re-checked against the allowlist after the script runs',
  /git status --porcelain[\s\S]{0,600}?safePath/.test(src));
ok('it refuses on trespass rather than warning', /trespass\.length\)\s*throw/.test(src));
ok('a plan that changes nothing is refused', /changed nothing/.test(src));
ok('the run target must be a file the plan itself wrote', /run target must be one of the files/.test(src));
ok('it only runs inside Actions', /GITHUB_ACTIONS !== 'true'/.test(src));
ok('it refuses to start on a dirty tree', /tree not clean/.test(src));
ok('the gate enumerates test files at run time', /readdirSync\(path\.join\(ROOT, 'scripts'\)\)/.test(src));
ok('a failed plan is closed, not retried forever', /will not be retried/.test(src));
ok('the pulse calls the applier before anything writes to the tree',
  /applyHandoffs\([\s\S]{0,200}?\n\n  const cases =/.test(fs.readFileSync(path.join(__dirname, 'poll.js'), 'utf8')));

console.log('\napply.test.js: ' + pass + ' assertions passed' + (fails.length ? ', ' + fails.length + ' FAILED' : ''));
if (fails.length) { fails.forEach(f => console.log('  FAIL  ' + f)); process.exit(1); }
